### ISSUE TITLE
Findings from fuzzing image/verify

### ISSUE THREAD

**Issue by benjamindoron** [chipsalliance/caliptra-sw#580]
Fuzzing image/verify with https://github.com/chipsalliance/caliptra-sw/pull/577 - specifically, libFuzzer - panics with the following:
`thread '<unnamed>' panicked at 'attempt to subtract with overflow', <caliptra-sw>/image/verify/src/verifier.rs:525:33`

**Comment by benjamindoron** [comment]
Also:

- `thread '<unnamed>' panicked at 'attempt to add with overflow', /home/benjamind/Downloads/Caliptra-SoC-RoT/caliptra-sw/image/verify/src/verifier.rs:535:33`
- `thread '<unnamed>' panicked at 'attempt to add with overflow', /home/benjamind/Downloads/Caliptra-SoC-RoT/caliptra-sw/image/verify/src/verifier.rs:537:37`

Fuzzing with struct-awareness additionally finds `thread '<unnamed>' panicked at 'attempt to add with overflow', /home/benjamind/Downloads/Caliptra-SoC-RoT/caliptra-sw/image/types/src/lib.rs:410:22`
