### ISSUE TITLE
Findings from fuzzing drivers/lms

### ISSUE THREAD

**Issue by benjamindoron** [chipsalliance/caliptra-sw#649]
Fuzzing the LMS implementation with https://github.com/chipsalliance/caliptra-sw/pull/618 - again, the libFuzzer feature enabled - triggers ASAN with the following:
`ERROR: AddressSanitizer: SEGV on unknown address 0x000000000004`

This is at `<caliptra-sw>/drivers/src/lms.rs:387:12`

**Comment by benjamindoron** [comment]
Using struct-aware fuzzing (or simply running for longer), the target panics with the following:
`thread '<unnamed>' panicked at 'attempt to add with overflow', <caliptra-sw>/drivers/src/lms.rs:393:33`

**Comment by benjamindoron** [comment]
I can't see where the bug uncovered by ASAN was fixed, that first line wasn't changed, but I can't make it trigger now either. Anyways, I found these in local runs while writing them, in the future, it'll come from CI.
